[package]
name = "proton"
version = "0.1.0"
authors = ["Nathan Sobo <nathan@github.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
proton-core = {path = "./proton-core"}
napi = {path = "./napi"}

[workspace]
