[package]
name = "xray"
version = "0.1.0"
authors = ["Nathan Sobo <nathan@github.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
xray_core = {path = "../xray_core"}
covalent = {path = "../../covalent"}
